### ISSUE TITLE
[Bug]领取邮件时得到的武器数量不正确

### ISSUE THREAD

**Issue by Cjjj-sys** [Qianyiovo/bread_dog_bot#3]
邮件中显示彩虹魔杖98个
但是领取后只得到了1个

可能是最大堆叠数量限制引起的Bug

**Comment by Arispex** [comment]
你好，目前还无法判断该物品是否为武器、装备等，导致邮箱中的物品数量显示异常。TShock中的give指令自动判断了该物品是否为武器、装备，如果是，数量会变成1，实际应用场景中，玩家不应该通过抽奖获得过多堆叠的武器，可能会带来一些不必要的麻烦（卖武器装备刷钱等）。后续版本中会修复此问题，感谢您的反馈。

**Comment by Arispex** [comment]
当时写的时候其实考虑到了，但是在机器人上判断可能比较麻烦，TShock有自动判断，就偷了个懒。

**Comment by Arispex** [comment]
没有疑问的话先关闭了
